### ISSUE TITLE
Issues with heads and signs not loading

### ISSUE THREAD

**Issue by m4s2firestorm** [tastybento/TopTenHeads#3]
First sign loads with skeleton head rest down and i get error, using 1.8.8 spigot with Newest version of Askyblock and 1.2 version of toptenheads

`
22.07 18:06:43 [Server] INFO m4s2firestorm issued server command: /placetopten 22.07 18:06:43 [Server] ERROR null 22.07 18:06:43 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'placetopten' in plugin TopTenHeads v1.2 22.07 18:06:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131] 22.07 18:06:43 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131] 22.07 18:06:43 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Skull.setOwningPlayer(Lorg/bukkit/OfflinePlayer;)V 22.07 18:06:43 [Server] INFO at com.wasteofplastic.toptenheads.LevelListener.displayTopTen(LevelListener.java:111) ~[?:?] 22.07 18:06:43 [Server] INFO at com.wasteofplastic.toptenheads.LevelListener.<init>(LevelListener.java:48) ~[?:?] 22.07 18:06:43 [Server] INFO at com.wasteofplastic.toptenheads.TopTenHeadsCommand.onCommand(TopTenHeadsCommand.java:102) ~[?:?] 22.07 18:06:43 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.07 18:06:43 [Server] INFO ... 15 more

**Comment by tastybento** [comment]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Skull.setOwningPlayer(Lorg/bukkit/OfflinePlayer;)

It looks like your server doesn't support the method in the Skull class to set the owning player. Sorry, I suppose 1.8.8 isn't supported.
